### ISSUE TITLE
Not working again :D

### ISSUE THREAD

**Issue by St4rl1ke** [Weesli/RClaim#5]
Hey i download the latest version of RClaim but it does nothing if i Type /claim

From the console

`: Error occurred while enabling RClaim v1.6 (Is it up to date?)
java.lang.RuntimeException: java.io.IOException: Das System kann den angegebenen Pfad nicht finden
        at net.weesli.rozsLib.database.sqlite.SQLiteBuilder.getDB(SQLiteBuilder.java:44) ~[?:?]
        at net.weesli.rozsLib.database.sqlite.SQLiteBuilder.build(SQLiteBuilder.java:34) ~[?:?]
        at net.weesli.rClaim.database.SQLiteStorage.<init>(SQLiteStorage.java:35) ~[?:?]
        at net.weesli.rClaim.RClaim.loadStorage(RClaim.java:141) ~[?:?]
        at net.weesli.rClaim.RClaim.onEnable(RClaim.java:63) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:267) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:492) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_21_R1.CraftServer.enablePlugin(CraftServer.java:567) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4226-Spigot-146439e-2889b3a]
        at org.bukkit.craftbukkit.v1_21_R1.CraftServer.enablePlugins(CraftServer.java:481) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4226-Spigot-146439e-2889b3a]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:641) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4226-Spigot-146439e-2889b3a]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:426) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4226-Spigot-146439e-2889b3a]
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:269) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4226-Spigot-146439e-2889b3a]
        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1017) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4226-Spigot-146439e-2889b3a]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4226-Spigot-146439e-2889b3a]
        at java.base/java.lang.Thread.run(Thread.java:1570) [?:?]
Caused by: java.io.IOException: Das System kann den angegebenen Pfad nicht finden
        at java.base/java.io.WinNTFileSystem.createFileExclusively0(Native Method) ~[?:?]
        at java.base/java.io.WinNTFileSystem.createFileExclusively(WinNTFileSystem.java:569) ~[?:?]
        at java.base/java.io.File.createNewFile(File.java:1045) ~[?:?]
        at net.weesli.rozsLib.database.sqlite.SQLiteBuilder.getDB(SQLiteBuilder.java:42) ~[?:?]`

**Comment by Weesli** [comment]
No plugins/RClaim/data/rclaim.db file?

If not, open the rclaim.db file yourself.

**Comment by St4rl1ke** [comment]
okay i dont get the data folder.
 i addet it but still dont work

**Comment by Weesli** [comment]
What you had to do was open a folder called data

I have released Version 1.6.1, the bug has been resolved.

**Comment by St4rl1ke** [comment]
Pefect :D now it works.

But if i try to upgrade the claim nothing happends

**Comment by Weesli** [comment]
Did you upgrade RozsLib?

**Comment by St4rl1ke** [comment]
Yes i used the latest version everything works only the upgrade doesnt

**Comment by Weesli** [comment]
Fixed
